eureka:
  instance:
    prefer-ip-address: true
  client: 
    fetch-registry: true # By default true
    register-with-eureka: true # By default true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
